### PR TITLE
Adding the "activate" opperation

### PR DESCRIPTION
**Pull request by callidus**
Adding an operation to activate keys on the HSM. This is prerequisite for key wrapping

### CODE REVIEW

**Comment by callidus** [comment]
looking at https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/tests/unit/services/test_kmip_client.py I dont see any tests for things that are similar to the new _activate method (client._destroy, client._register) etc. Am I missing something here?

**Comment by PeterHamilton** [comment]
Gah, no, you're right. I thought I'd put in some tests for the `query` related methods but it looks like I never did. You can ignore that for now, I'll add them to my list.

**Comment by PeterHamilton** [comment]
The docstrings and factory tests look good. Once you've got the payload tests in place, please squash all of your commits into a single final commit and I'll give it a final review. Thanks!

**Comment by callidus** [comment]
let me know if anything looks amiss or needs adding. Im now starting working on the counterpart revoke operation.

**Comment by PeterHamilton** [comment]
Will do. I'll try to review this in the next couple of hours.

**Comment by PeterHamilton** [comment]
This all looks good to me. Just update the one docstring and I'll run it through some tests. Once those pass, I'll merge it in.

**Comment by callidus** [comment]
done

**Comment by PeterHamilton** [comment]
:+1: Works like a charm. Thanks for this!

**Comment by callidus** [comment]
wonderful, thanks Peter

**Pull request merged**
