### PR TITLE
Allow custom attributes

### PR DESCRIPTION
**Pull request by locula**
Add the ability to create and store custom attributes for SecretData objects and ensure that they are stored on the KMIP server when the register function is called

### CODE REVIEW

**Comment by locula** [comment]
@PeterHamilton could you please approve the workflow run?

**Comment by PeterHamilton** [comment]
> @PeterHamilton could you please approve the workflow run?

Sure! I'd forgotten initial workflows need approval.

Thanks for the submission, by the way. I'll review it later today.

**Comment by locula** [comment]
Hi @PeterHamilton, did you get a chance to review my submission?

**Comment by PeterHamilton** [comment]
@locula Yes, thanks for the reminder. This is simple enough that it looks good to me.

**Pull request merged**
