### PR TITLE
Adding MAC operation(client/server) and related unit tests

### PR DESCRIPTION
**Pull request by vbnmmnbv**
I didn’t add any integration test because currently I can not make integration test work due to some sqlalchemy  failure. But all the unit tests and manual integration test(manually spinning up the server and sending MAC request from client) work fine.

### CODE REVIEW

**Comment by vbnmmnbv** [comment]
er.... PEP8 failed.... Is it a hard requirement to make PEP8 check pass? Please let me know so that I can refactor it~

**Comment by PeterHamilton** [comment]
Yes, the pull request must pass all checks and tests to be accepted, including `pep8`.

While you're at it, you should split this pull request into several smaller ones (it is over 900+ line changes after all). Let's break it down like this:

1. A PR for the updates to the cryptography engine, with its tests
2. A PR for the updates to the KMIPProxy client, with its tests
3. A PR for the updates to the ProxyKmipClient, with its tests
4. A PR for the updates to the server engine, with its tests

That will make it easier to review and manage any changes or updates that may be needed.

**Comment by PeterHamilton** [comment]
Also, let me know what failure you're seeing with the integration tests. I made sure they worked with the PyKMIP server a few weeks ago, so if there are still problems with them I'd love to get them fixed.

**Comment by vbnmmnbv** [comment]
Hi Peter,

For the 4 pull requests you want, I think they are not totally independent.
For example, both client and server need MACRequestPayload. 

I am new to Github:) Can you give me some guide on how to make them into 4 pull requests as they are related? To be specific, for example, which pull should include MACRequestPayload?

**Comment by PeterHamilton** [comment]
Sure. You are correct, they are not independent. The main idea is to post these in stages, not all at once.

You start off by posting the cryptography engine pull request (1) and the KMIPProxy client pull request (2) first (since they don't directly relate to each other), including in each one everything needed to make the changes and tests work for those pull requests (for example, MACRequest/ResponsePayload would go in (2)). Once those two pull requests merge, you post the ProxyKmipClient pull request (3). Since (3) relies on (2), all of (3)'s dependencies will already be merged; all you need to do is make sure any remaining changes needed for (3) are included with it. Once (1), (2), and (3) are merged in, you can post the server pull request (4).

The main thing to watch out for here is including duplicate code across pull requests. Sometimes Git will handle this just fine but usually it will trigger a merge conflict, requiring you to go into the newer pull request and remove the duplicate code or restructure it so that it doesn't conflict with the rest of the code base.

This is generally how I try to add in new features that cross the clients and server, though I sometimes will do (2) and (3) in one patch if the additions are small enough. It varies. There are plenty of examples in the project commit history.

The core idea is to make things as easy for the developer and the reviewer(s) as possible, to help them ensure that the code is correct before officially merging it in. The larger a patch is, the easier it is for bugs to slip through. That's really all there is to it.

**Comment by PeterHamilton** [comment]
Also (before I forget), I also like to squash my commits for a single change into one commit for the pull request; it leaves the commit history for `master` in a cleaner state. For example, for the `pep8` fixes, once you make those you can simply do a `git commit --amend` to add your changes into the previous commit.

This isn't absolutely required but it matches how we generally work on PyKMIP.

**Pull request closed without merging**
