### PR TITLE
Unit test fixes

### PR DESCRIPTION
**Pull request by cfs-pure**
Fix unittests for compatibility between Python 2 and 3.
Fixed a mock for open() in kmip.services.server.server

### CODE REVIEW

**Comment by cfs-pure** [comment]
The problems this pull request fixed came up when rebuilding the python-pykmip package from Ubuntu zesty ([0.5.0-4](http://packages.ubuntu.com/source/zesty/python-pykmip)) using the v0.6.0 tarball from PyPI.  The Debian build uses python-coverage and not tox.

**Comment by PeterHamilton** [comment]
I'm fine with the `six.assertCountEqual` and `six.assertRaisesRegex` changes. Can you provide more info on the `mock.patch` change with `create=True`? Was `open` not found when you were running the tests?

**Comment by cfs-pure** [comment]
@PeterHamilton the mock was being applied to the kmip.services.server.server class which does not have an open method.

**Comment by PeterHamilton** [comment]
I think the `open` issue will be better handled if I just switch to using `mock_open`. I'll put out a patch for that. Once that's in, you can pull out the `mock.patch` change and this should be good to go.

**Comment by PeterHamilton** [comment]
Nevermind, I'm already using `mock_open`. The right solution is to scrap the code in the `try` block and just use the right module for Python 3+, `builtins`.

**Comment by PeterHamilton** [comment]
See PR https://github.com/OpenKMIP/PyKMIP/pull/239 for the open mock fix.

**Comment by PeterHamilton** [comment]
PR https://github.com/OpenKMIP/PyKMIP/pull/239 has been merged. Once this PR is updated, I'll merge it as well.

**Comment by cfs-pure** [comment]
Removed my changes to test_server.py because of #239.

**Pull request merged**
