### PR TITLE
server: implement 'discover-versions'

### PR DESCRIPTION
**Pull request by viktorTarasov**
* proposed support of _DiscoverVersions_ operation by server
* trying to satisfy the _Codecov_ part of CI,
   ventured to propose some kind of semi-integration test for _server.processor_

### CODE REVIEW

**Comment by PeterHamilton** [comment]
This looks good. Thanks for adding that initial processor test suite; it's something that's been on my todo list for a while now. Go ahead and address the comments and this should be good to go.

**Comment by viktorTarasov** [comment]
resolving remarques of @PeterHamilton:
* _log.warning_ changed for _log.debug_;
* commented test procedures.

**Comment by viktorTarasov** [comment]
fixed typo in comments

**Comment by PeterHamilton** [comment]
:+1: LGTM!

**Pull request merged**
