### PR TITLE
Adding revoke operation

### PR DESCRIPTION
**Pull request by callidus**
Adding Revoke opperation

### CODE REVIEW

**Comment by PeterHamilton** [comment]
I'm just curious: why do you need these operations and (maybe more importantly) how are you using them? I want to make sure I test them appropriately. Thanks!

**Comment by callidus** [comment]
Ultimately I am working on key wrapping. I cant use a key on the HSM until it is in the active state, hence needing activate. It would seem that an activated key can then not be destroyed, so I needed the revoke operation to deactivate them prior to destruction.

**Comment by callidus** [comment]
Setting the activation date attributes on a key will cause the server to automatically mark it active within a given window, but I needed something more add-hoc for my prepossess

**Comment by callidus** [comment]
looks like I'll need to rebase this. I'll do it now

**Comment by callidus** [comment]
rebased

**Comment by PeterHamilton** [comment]
Yep, I can confirm that activating a secret blocks any destroy operation on it, at least from the client. Adding revoke definitely makes sense.

I'll try to review this one today as well. I never seem to have as much time as I think I will when I sit down to review things.

**Comment by callidus** [comment]
I know that feeling all too well! Thanks for looking this over

**Pull request merged**
